version: '3.8'

services:
  apache:
    image: php:8.1-apache
    container_name: lamp_apache
    volumes:
      - ./studenti:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: lamp_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studenti
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306" # Corect: Portul containerului MySQL este 3306
    volumes:
      - db_data:/var/lib/mysql

volumes: # Corect: Această secțiune trebuie să fie la nivelul rădăcină (fără indentare)
  db_data: